package com.dpbird.drools
import com.dpbird.workflow.WorkFlow;
import com.dpbird.workflow.Activity;

dialect "java"

rule "First Activity"
    when
        $workFlow : WorkFlow(statusId == WorkFlow.WF_STATUS_PLANNING)
    then
        modify($workFlow) {
            setStatusId(WorkFlow.WF_STATUS_IN_PROGRESS),
            setActiveName("reviewer")
        };
end

rule "Review Activity"
    when
        $workFlow : WorkFlow(statusId == WorkFlow.WF_STATUS_IN_PROGRESS)
        $activeActivity : Activity(statusId == WorkFlow.WF_STATUS_COMPLETE, activityName == "reviewer") from $workFlow.activeActivities
    then
        modify($workFlow) {
            setActiveName("approver")
        };
end

rule "Approve Activity"
    when
        $workFlow : WorkFlow(statusId == WorkFlow.WF_STATUS_IN_PROGRESS)
        $activeActivity : Activity(statusId == WorkFlow.WF_STATUS_COMPLETE, activityName == "approver") from $workFlow.activeActivities
    then
        modify($workFlow) {
            setStatusId(WorkFlow.WF_STATUS_COMPLETE)
        };
end
