package com.dpbird.drools
import com.dpbird.workflow.WorkFlow;
import com.dpbird.workflow.Activity;

rule "First Activity"
    dialect "mvel"
    when
        workFlow : WorkFlow(statusId == "WEPR_PLANNING")
    then
        modify ( workFlow ) { statusId = "WEPR_IN_PROGRESS",
                       activeName = "reviewer" };
end

rule "Review Activity"
    dialect "mvel"
    when
        workFlow : WorkFlow(statusId == "WEPR_IN_PROGRESS")
        activity : Activity(statusId == "WEPR_COMPLETE", activityName == "reviewer")
    then
        modify ( workFlow ) { activeName = "approver" };
end

rule "Approve Activity"
    dialect "mvel"
    when
        workFlow : WorkFlow(statusId == "WEPR_IN_PROGRESS")
        activity : Activity(statusId == "WEPR_COMPLETE", activityName == "approver")
    then
        modify ( workFlow ) { statusId = "WEPR_COMPLETE" };
end
